application: gdn-stack-ranking
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: static
- url: /admin/.*
  script: admin.app
  login: admin
  secure: always
- url: /api/.*
  script: api.app
  secure: always
  login: required
- url: /.*
  script: app.app
  secure: always
  login: required

libraries:
- name: jinja2
  version: latest

skip_files:
- ^(.*/)?.*/node_modules/.*$